import Head from "next/head";
import { Landing } from "../../components/Landing";
import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Artsts</title>
        <meta name="description" content="Generated by Fannie for ETH Global" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
    </div>
  );
};

export default Home;
